# ==========================================================================================
# Author: Pablo González García.
# Created: 22/01/2026
# Last edited: 22/01/2026
# ==========================================================================================


# ==============================
# DEFAULT
# ==============================

name: "bge_m3_tokenizer"
backend: "python"
max_batch_size: 32


# ==============================
# INPUTS
# ==============================

input [
    {
        name: "TEXT"
        data_type: TYPE_STRING
        dims: [ -1 ]
    }
]


# ==============================
# OUTPUTS
# ==============================

output [
    {
        name: "input_ids"
        data_type: TYPE_INT64
        dims: [ -1 ]
    },
    {
        name: "attention_mask"
        data_type: TYPE_INT64
        dims: [ -1 ]
    }
]