# ==========================================================================================
# Author: Pablo González García.
# Created: 22/01/2026
# Last edited: 22/01/2026
# ==========================================================================================


# ==============================
# DEFAULT
# ==============================

name: "bge_m3_ensemble"
platform: "ensemble"
max_batch_size: 32


# ==============================
# INPUTS
# ==============================

input [
    {
        name: "TEXT"
        data_type: TYPE_STRING
        dims: [ 1 ]
    }
]


# ==============================
# OUTPUTS
# ==============================

output [
    {
        name: "EMBEDDING"
        data_type: TYPE_FP32
        dims: [ 1024 ]
    }
]


# ==============================
# SCHEDULING
# ==============================

ensemble_scheduling {
    step [
        {
            model_name: "bge_m3_tokenizer"
            model_version: -1

            input_map {
                key: "TEXT"
                value: "TEXT"
            }

            output_map {
                key: "input_ids"
                value: "INPUT_IDS"
            }

            output_map {
                key: "attention_mask"
                value: "ATTENTION_MASK"
            }
        },
        {
            model_name: "bge_m3_model"
            model_version: -1
            
            input_map {
                key: "input_ids"
                value: "INPUT_IDS"
            }

            input_map {
                key: "attention_mask"
                value: "ATTENTION_MASK"
            }

            output_map {
                key: "sentence_embedding"
                value: "EMBEDDING"
            }
        }
    ]
}