# ==========================================================================================
# Author: Pablo González García.
# Created: 19/01/2025
# Last edited: 19/01/2026
# ==========================================================================================


# ==============================
# DEFAULT
# ==============================

name: "distilbert_base_multilingual_cased"
backend: "onnxruntime_onnx"