# ==========================================================================================
# Author: Pablo González García.
# Created: 19/01/2025
# Last edited: 19/01/2026
# ==========================================================================================


# ==============================
# DEFAULT
# ==============================

name: "multilingual_e5_base"
backend: "onnxruntime_onnx"